version: '3'
services:
  dev:
    image: node:12
    volumes:
      - nodemodules:/usr/src/service/node_modules
      - .:/usr/src/service
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    working_dir: /usr/src/service
    command: npm run dev
    ports:
      - 1234:1234
      - 1235:1235

volumes:
  nodemodules:
    external: true
